# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Gwenaëlle et Pierre
email: thi.suzanne@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Site du mariage de Gwenaëlle et Pierre
baseurl: "/site-mariage-GwenaelleEtPierre" # the subpath of your site, e.g. /blog
url: "http://site-mariage.github.io/site-mariage-GwenaelleEtPierre" # the base hostname & protocol for your site
github_username:  thizanne

# Build settings
markdown: kramdown

# Global variables
url-liste: http://www.millemercismariage.com/gwenaetpierre/liste.html
